name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  NEXT_PUBLIC_SITE_NAME: "Incubizo"
  NEXT_PUBLIC_SITE_DESCRIPTION: "A business incubator and innovation hub helping startups grow through innovation, mentorship, and strategic partnerships."
  NEXT_PUBLIC_SITE_URL: "https://grayghostdev.github.io/incubizo-website"
  NEXT_PUBLIC_GITHUB_URL: "https://github.com/GrayGhostDev/incubizo-website"
  NEXT_PUBLIC_CONTACT_EMAIL: "info@incubizo.com"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build with Next.js
        run: npm run build
        env:
          # Additional build-time environment variables
          NEXT_PUBLIC_BUILD_TIME: ${{ github.event.repository.updated_at }}
          NEXT_PUBLIC_GITHUB_REPOSITORY: ${{ github.repository }}
          NEXT_PUBLIC_GITHUB_SHA: ${{ github.sha }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./out
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 